# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U_lnDPW7b2HwWHCmncGcVRLBcYdcdAYJ
"""

# config.py

TOKEN = "8544100639:AAG9YamM6DJeWM7AKQfnAIIoKGjQ61wfLwQ"  # Замените на токен вашего бота

CURRENCY_API_URL = "https://www.cbr-xml-daily.ru/daily_json.js"


SUPPORTED_CURRENCIES = {
    "USD": "Доллар США",
    "EUR": "Евро",
    "GBP": "Фунт стерлингов",
    "JPY": "Японская иена",
    "CNY": "Китайский юань",
    # Добавьте другие валюты по необходимости
}