# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U_lnDPW7b2HwWHCmncGcVRLBcYdcdAYJ
"""

# extensions.py

import requests
import json
from datetime import datetime



class APIException(Exception):
    """Пользовательское исключение для ошибок API и ввода пользователя."""
    pass



class CurrencyConverter:
    @staticmethod
    def get_price(base: str, quote: str, amount: float) -> tuple[float, str]:
        if base not in SUPPORTED_CURRENCIES:
            raise APIException(f"Валюта {base} не поддерживается.")
        if quote not in SUPPORTED_CURRENCIES:
            raise APIException(f"Валюта {quote} не поддерживается.")

        try:
            response = requests.get(CURRENCY_API_URL)
            response.raise_for_status()
            data = response.json()
        except requests.exceptions.RequestException as e:
            raise APIException(f"Ошибка API: {e}")
        except json.JSONDecodeError as e:
            raise APIException(f"Ошибка JSON: {e}")

        raw_date = data["Date"]

        # Исправление формата даты
        if 'T' in raw_date and len(raw_date) > 19:
            base_part = raw_date[:19]
            offset_part = raw_date[19:]
            if offset_part and (offset_part[0].isdigit() or offset_part.startswith('0')):
                offset_part = '+' + offset_part
            fixed_date_str = base_part + offset_part
        else:
            fixed_date_str = raw_date

        try:
            date_obj = datetime.fromisoformat(fixed_date_str)
        except ValueError as e:
            raise APIException(f"Некорректная дата в API: {raw_date} ({e})")

        formatted_date = date_obj.strftime("%d.%m.%Y")

        valutes = data["Valute"]
        if base not in valutes:
            raise APIException(f"Курс {base} не найден.")
        if quote not in valutes:
            raise APIException(f"Курс {quote} не найден.")

        base_to_rub = valutes[base]["Value"]
        quote_to_rub = valutes[quote]["Value"]

        result = amount * base_to_rub / quote_to_rub
        return round(result, 2), formatted_date