# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U_lnDPW7b2HwWHCmncGcVRLBcYdcdAYJ
"""

# main.py

import telebot
from config import TOKEN, SUPPORTED_CURRENCIES
from extensions import CurrencyConverter, APIException


# Инициализация бота
bot = telebot.TeleBot(TOKEN)


# Обработчик команд /start и /help
@bot.message_handler(commands=["start", "help"])
def handle_start_help(message):
    text = (
        "Привет! Я бот для конвертации валют.\n\n"
        "Чтобы узнать цену, отправьте сообщение в формате:\n"
        "<валюта1> <валюта2> <количество>\n\n"
        "Примеры:\n"
        "USD EUR 100\n"
        "EUR RUB 50\n\n"
        "Доступные валюты:\n"
    )
    for code, name in SUPPORTED_CURRENCIES.items():
        text += f"{code} — {name}\n"
    text += "\nИспользуйте /values, чтобы увидеть список валют."
    bot.send_message(message.chat.id, text)

# Обработчик команды /values
@bot.message_handler(commands=["values"])
def handle_values(message):
    text = "Поддерживаемые валюты:\n"
    for code, name in SUPPORTED_CURRENCIES.items():
        text += f"{code} — {name}\n"
    bot.send_message(message.chat.id, text)

# Обработчик текстовых сообщений (конвертация валют)
@bot.message_handler(content_types=["text"])
def handle_convert(message):
    try:
        # Разбиваем сообщение на части
        parts = message.text.strip().split()
        if len(parts) != 3:
            raise APIException("Неверный формат. Ожидается: <валюта1> <валюта2> <количество>")

        base, quote, amount_str = parts

        # Проверяем, что количество — число
        try:
            amount = float(amount_str)
        except ValueError:
            raise APIException("Количество должно быть числом.")

        # Получаем цену и дату курса
        result, rate_date = CurrencyConverter.get_price(base.upper(), quote.upper(), amount)

        # Формируем ответ
        text = (
            f"{amount} {base.upper()} = {result} {quote.upper()}\n"
            f"Курс актуален на: {rate_date}"
        )
        bot.send_message(message.chat.id, text)

    except APIException as e:
        bot.send_message(message.chat.id, f"Ошибка: {e}")
    except Exception as e:
        bot.send_message(message.chat.id, f"Неизвестная ошибка: {e}")

# Запуск бота
if __name__ == "__main__":
    print("Бот запущен...")
    bot.polling(none_stop=True)